config/routes.rb
Pdigital::Application.routes.draw do

  match '/rss' => 'articles#rss'

  scope "/(:locale)" do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    devise_for :users
    match 'the_mosts/day' => 'the_mosts#day', :as => :day
    match 'the_mosts/month' => 'the_mosts#month', :as => :month
    match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
      
    resources :articles, :categories, :polls, :the_mosts, :contact, :comments, :real_time, :calendar, :events, :debates, :commerces

    match 'search/' => 'articles#search'
    
    root :to => 'articles#index'
    
    match 'contact' => 'contact#new', :as => 'contact', :via => :get
    match 'contact' => 'contact#create', :as => 'contact', :via => :post
    
  end

  match 'comments/vote/:id/:vote_type' => 'comments#vote', :as => :vote
  match 'comments/delete/:id' => 'comments#delete', :as => :delete
  
  match 'polls/vote/:id/:id_option' => 'polls#vote', :as => :vote_poll
  match 'polls/vote_result/:id' => 'polls#vote_result', :as => :vote_result
  match 'polls/poll_options/:id' => 'polls#poll_options', :as => :poll_options
  
  mount ImperaviRails::Engine => "/imperavi"
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, :polymorphic => true
  belongs_to :article
  belongs_to :user
  belongs_to :debate
  has_many :votes
  before_save :clean
  
  validates :body, :presence => true
  validates :body, :length => { :minimum => 2 }
  validates :body, :uniqueness => { :scope => [:user_id, :commentable_id, :active] }
  
  def vote(type, ip)
    self.votes.create! :vote_type => type, :ip => ip
  end
  
  def delete
    self.active = false
    self.save!
  end
  
  def vots_result
    positive = self.votes.where(:vote_type => 1)
    negative = self.votes.where(:vote_type => 2)
    total = positive.count - negative.count
    return total
  end
  
  def voted(ip)
    voted = self.votes.where(:ip => ip)
    if voted.count == 0
      return false
    else
      return true
    end
  end
  
  def show_body 
    my_body = self.body.gsub(/\n/, '<br>')
  end


  private
  
  def clean
    self.body = Sanitize.clean(self.body, :elements => ['a','b','br'])
  end
  
  
end
  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  skip_before_filter :store_location
  
  def create
      @comment = Comment.new(:body => params[:comment][:body], 
                                            :user => current_user,
                                            :active => true, 
                                            :commentable_id => params[:comment][:id], 
                                            :commentable_type => params[:comment][:type])
                              
      @commentable = @comment.commentable
      
    if simple_captcha_valid?
      respond_to do |format|
        if @comment.save
          
          RealTime.create!  :trackeable_id => @comment.id, 
                            :trackeable_type => "Comment", 
                            :subtype => @commentable.class.to_s, 
                            :user_id => current_user.id
                            
          format.html { redirect_to @commentable, notice: t(:comment_succefull) }
        else
          format.html { redirect_to :back, alert: t(:comment_error) }
        end
      end
    else
      respond_to do |format|
          format.html { redirect_to :back, alert: t(:captcha_error)}
      end
    end
  end
  
  def vote
    @comment = Comment.find(params[:id])
    vote = @comment.vote(params[:vote_type], request.ip) if @comment
    
    # RealTime.create!  :trackeable_id => @comment.commentable, 
    #                       :trackeable_type => "Vote", 
    #                       :subtype => @comment.commentable.class.to_s, 
    #                       :user_id => nil,
    #                       :object_id => @comment.commentable.id if vote
                              
    respond_to do |format|
      format.js
    end
  end
  
  def delete
    @comment = Comment.find(params[:id])
            
    if @comment.user == current_user and @comment.created_at+15.minutes > Time.now
      @comment.delete
    end
    
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  
  def vote_status(comment)
    if comment > 0
      return "positive"
    end
    if comment < 0
      return "negative"
    end
    if comment == 0
      return "neutral"
    end
  end
  
  def delete_actions(comment)
    if current_user.present? and comment.user.present? and comment.created_at+15.minutes > Time.now
      if current_user.username == comment.user.username
        "onmouseover='javascript:show_delete_comment(#{comment.id})' onmouseout='javascript:hide_delete_comment(#{comment.id})'"
      end
    end
  end
end

app/views/comments/_box.html.erb
<% if @comments.empty? %>

	<div class="comment_box">
		<div class="comment_body"><%=t(:no_comments)%></div>
	</div>

<% else %>

	<% comment_number = 0 %>
	<% @comments.each do |comment| %>
	
		<div id="comment_<%= comment.id %>" class="comment_box" <%= delete_actions(comment) %>>
			
			<div class="comment_header">#<%= comment_number+=1 %> 
				<span class="comment_author">
					<%= comment.user.username if comment.user != nil %>
					<%= comment.username if comment.user == nil %>
				</span> - <%= comment.created_at.strftime("%d/%m/%Y "+t(:at)+" %H:%M") %>
				<%= link_to raw("<span class='delete'>eliminar</span>"), delete_url(comment.id), :remote => true, :confirm => "Segur que vols esborrar aquest missatge?" %>
			</div>			
			<div class="comment_body"><%= auto_link(raw(comment.body.gsub(/\n/, '<br>')), :html => { :target => '_blank' }) %></div>
			<div class="comment_social <%= "comment#{comment.id}" %>">
				
			<%= render :partial => 'comments/votes', :locals => {:comment => comment} %>
			
			</div>
		</div>

	<% end %>

<% end %>

app/views/comments/_form.html.erb
<div id="comment_form">
	<%= form_tag(comments_path, :method => "POST") do %>
		<%= text_area(:comment, :body, :rows => 3, :class => "textarea_comment") %><br />
		<%= hidden_field(:comment, :id, :value => id) %>
		<%= hidden_field(:comment, :type, :value => type ) %>
		<%= show_simple_captcha %>
		
		<div class="disclaimer"><%=t(:comment_responsability) %></div>
		<%= submit_tag(t(:send), :class => "btn-primary btn-large") %>
	<% end %>
</div>

app/views/comments/_show.html.erb
<div id="comments_header"><%=t(:comments)%></div>

<% require 'rails_autolink' %>
<%= render :partial => 'comments/box'%>

<div id="comments_header"><%=t(:add_comment)%></div>

<% if user_signed_in? %>
	<p><%=t(:logged_as)%> <b><%= current_user.username %></b>. <%=t(:if_not_you)%> <%= link_to t(:sign_out), destroy_user_session_path, :method => :delete %>.</p>
	
	<%= @fail_comment %>
	
	<%= render :partial => 'comments/form', :locals => {:id => id, :type => type} %>

<% else %>
	
	<p><%=t(:user_required_comments)%></p>
	 <%= link_to t(:register), new_user_registration_path %> <%=t(:or)%> <%= link_to t(:sign_in), new_user_session_path %>
	
<% end %>

app/views/comments/_votes.html.erb
<% if comment.voted(request.remote_ip) == false %>
<%= link_to image_tag('ico/good.png', :valign => '-6px'), vote_url(comment,1), :remote => true %> 
<%= link_to t(:vote_ok), vote_url(comment,1),  :remote => true, :class => "vote", :id => "vote_ok" %> | 
<%= image_tag "ico/bad.png", :valign => "-6px" %> 
<%= link_to t(:vote_ko), vote_url(comment,2), :remote => true , :id => "vote_ko" %>.
<span class="result_vot <%= vote_status(comment.vots_result)%>"><%= comment.vots_result %></span><span class="total_vot"> (<%= comment.votes.count %> <%=t(:votes)%>)</span>
<% else %>
<%=t(:voted)%> <span class="result_vot <%= vote_status(comment.vots_result)%>"><%= comment.vots_result %></span><span class="total_vot"> (<%= pluralize(comment.votes.count,t(:singular_vote),t(:plural_votes))%>)</span>
<% end %>

app/views/comments/delete.js.erb
$("#comment_<%=@comment.id %>").fadeOut();

app/views/comments/vote.js.erb
$(".comment<%=@comment.id %>").html("<%= escape_javascript(render(:partial => 'comments/votes', :locals => { :comment => @comment} )) %>");