config/routes.rb
Pdigital::Application.routes.draw do

  match '/rss' => 'articles#rss'

  scope "/(:locale)" do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    devise_for :users
    match 'the_mosts/day' => 'the_mosts#day', :as => :day
    match 'the_mosts/month' => 'the_mosts#month', :as => :month
    match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
      
    resources :articles, :categories, :polls, :the_mosts, :contact, :comments, :real_time, :calendar, :events, :debates, :commerces

    match 'search/' => 'articles#search'
    
    root :to => 'articles#index'
    
    match 'contact' => 'contact#new', :as => 'contact', :via => :get
    match 'contact' => 'contact#create', :as => 'contact', :via => :post
    
  end

  match 'comments/vote/:id/:vote_type' => 'comments#vote', :as => :vote
  match 'comments/delete/:id' => 'comments#delete', :as => :delete
  
  match 'polls/vote/:id/:id_option' => 'polls#vote', :as => :vote_poll
  match 'polls/vote_result/:id' => 'polls#vote_result', :as => :vote_result
  match 'polls/poll_options/:id' => 'polls#poll_options', :as => :poll_options
  
  mount ImperaviRails::Engine => "/imperavi"
  

end

app/controllers/the_mosts_controller.rb
class TheMostsController < ApplicationController
  def index
    @articles_commented = Article.get_comments(:comments_count)
    @articles_viewed = Article.get_comments
    
    respond_to do |format|
      format.html # index.html.erb
    end
    
  end
  
  def day
    @articles_commented = Article.get_comments(:comments_day)
    @articles_viewed = Article.get_comments(:views_day)
    
    respond_to do |format|
      format.html # day.html.erb
    end
  end
  
  def month
     @articles_commented = Article.get_comments(:comments_month)
     @articles_viewed = Article.get_comments(:views_month)

     respond_to do |format|
       format.html # month.html.erb
     end
   end
  
end

app/helpers/the_mosts_helper.rb
module TheMostsHelper
end

app/views/the_mosts/_most_box.html.erb
<%= stylesheet_link_tag    "the_mosts" %>

<% articles.each do |article| %>
	<div class="mostBoxContent">
		<div class="article_title"><%= link_to article.title, article_path(article) %></div>
		<div style="margin-bottom:5px;">
			<span class="article_author"><%= article.author.upcase %></span>
			<span class="article_date">&nbsp;&nbsp;|&nbsp;&nbsp;<%= article.category.name %> - <%= article.published_date %></span>
		</div>
		<div class="article_img_div">	
		<% if(article.images.first) %>
			<%= link_to (image_tag article.images.first.image.url(:medium) , :class => "article_img", :border => 0), article_path(article) %>
		<% end %>
		</div>
		<div class="article_info">
			<div class="article_comments">
				<%= image_tag "ico/comment.png", :class => "thumb_img" %> <%= pluralize(article.comments.where(:active => true).count,t(:singular_comment),t(:plural_comments)) %>
			</div>
		</div>
	</div>
<% end %>

app/views/the_mosts/_structure.html.erb
<%= stylesheet_link_tag    "the_mosts" %>

<div class="buttons">
	<%= link_to raw("<span class='btn #{'btn-primary' if controller.action_name == 'day'}'>#{t(:day)}</span>"), day_url() %>
	<%= link_to raw("<span class='btn #{'btn-primary' if controller.action_name == 'month'}'>#{t(:month)}</span>"), month_url() %>
	<%= link_to raw("<span class='btn #{'btn-primary' if controller.action_name == 'index'}'>#{t(:allways)}</span>"), the_mosts_url() %>
</div>

<div class="row">
	<div class="span4">
		<p class="mostTitle"><%= t(:more_commented)%></p>
		<%= render :partial => 'most_box', :locals => {:articles => @articles_commented} %>
	</div>
	<div class="span4">
		<p class="mostTitle"><%= t(:more_viewed)%></p>
		<%= render :partial => 'most_box', :locals => {:articles => @articles_viewed} %>
	</div>
	<div class="span4">
		<%= render :partial => 'articles/banner', :locals => {:ad_zone => Configuration.value(:openx_inner_zone_a), :ad_code => Configuration.value(:openx_inner_code_a)} %>	
		<br />
		<%= render :partial => 'articles/banner', :locals => {:ad_zone => Configuration.value(:openx_inner_zone_b), :ad_code => Configuration.value(:openx_inner_code_b)} %>
		<br />
		<%= render :partial => 'articles/banner', :locals => {:ad_zone => Configuration.value(:openx_inner_zone_c), :ad_code => Configuration.value(:openx_inner_code_c)} %>
	</div>
</div>

app/views/the_mosts/day.html.erb
<%= render :partial => 'structure' %>

app/views/the_mosts/index.html.erb
<%= stylesheet_link_tag    "the_mosts" %>

<br />
<div class="row">
	<div class="span4">
		<p class="mostTitle"><%= t(:more_commented)%></p>
		<%= render :partial => 'most_box', :locals => {:articles => @articles_commented} %>
	</div>
	<div class="span4">
		<p class="mostTitle"><%= t(:more_viewed)%></p>
		<%= render :partial => 'most_box', :locals => {:articles => @articles_viewed} %>
	</div>
	<div class="span4">
		<%= render :partial => 'articles/banner', :locals => {:ad_zone => Configuration.value(:openx_inner_zone_a), :ad_code => Configuration.value(:openx_inner_code_a)} %>	
		<br />
		<%= render :partial => 'articles/banner', :locals => {:ad_zone => Configuration.value(:openx_inner_zone_b), :ad_code => Configuration.value(:openx_inner_code_b)} %>
		<br />
		<%= render :partial => 'articles/banner', :locals => {:ad_zone => Configuration.value(:openx_inner_zone_c), :ad_code => Configuration.value(:openx_inner_code_c)} %>
	</div>
</div>

app/views/the_mosts/month.html.erb
<%= render :partial => 'structure' %>