config/routes.rb
Pdigital::Application.routes.draw do

  match '/rss' => 'articles#rss'

  scope "/(:locale)" do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    devise_for :users
    match 'the_mosts/day' => 'the_mosts#day', :as => :day
    match 'the_mosts/month' => 'the_mosts#month', :as => :month
    match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
      
    resources :articles, :categories, :polls, :the_mosts, :contact, :comments, :real_time, :calendar, :events, :debates, :commerces

    match 'search/' => 'articles#search'
    
    root :to => 'articles#index'
    
    match 'contact' => 'contact#new', :as => 'contact', :via => :get
    match 'contact' => 'contact#create', :as => 'contact', :via => :post
    
  end

  match 'comments/vote/:id/:vote_type' => 'comments#vote', :as => :vote
  match 'comments/delete/:id' => 'comments#delete', :as => :delete
  
  match 'polls/vote/:id/:id_option' => 'polls#vote', :as => :vote_poll
  match 'polls/vote_result/:id' => 'polls#vote_result', :as => :vote_result
  match 'polls/poll_options/:id' => 'polls#poll_options', :as => :poll_options
  
  mount ImperaviRails::Engine => "/imperavi"
  

end

app/views/shared/_alerts.html.erb
<% if notice.blank? %>
<% else %>

	<div class="alert alert-success fade in">
	  <a class="close" data-dismiss="alert" href="#">×</a>
	  <p><%= notice %></p>
	</div>
<% end %>

<% if alert.blank? %>
<% else %>

	<div class="alert alert-error fade in">
	  <a class="close" data-dismiss="alert" href="#">×</a>
	  <p><%= alert %></p>
	</div>
<% end %>
	

app/views/shared/_analitycs_code.html.erb
<script type="text/javascript">
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', '<%= raw(Configuration.value(:analytics_tracking))%>']);
	_gaq.push(['_trackPageview']);

	(function() {
	  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();
</script>

app/views/shared/_categories.html.erb
<div class="category_bar">
	<% Category.all.each do |category| %>
	<%= link_to category.name, category_path(category) %>
	<%= "<span class='category_separator'>|</span>".html_safe unless Category.last == category %>
	<% end %>
</div>

app/views/shared/_facebook_tags.html.erb
<% if @article.present? %>

	<meta property='og:title' content='<%= @article.title.gsub(/'/, "") %>' />
	<meta property='og:description' content='<%= @article.resume.gsub(/'/, "") %>' />
	<meta property='og:type' content='article' />
	<meta property='og:url' content='<%= request.protocol+request.host+request.fullpath %>' />
	
	<% if @article.images.first %>
		<meta property='og:image' content='<%= request.protocol+request.host+@article.images.first.image.url(:facebook) %>'/>
	<% else %>
		<meta property='og:image' content='<%= request.protocol+request.host+Configuration.image_url(:image_site) %>'/>
	<% end %>
	
	<meta property='og:site_name' content='<%=Configuration.value(:sitename)%>' />
	
<% elsif @event.present?%>
	<% if @event.title.present? %>
	<meta property='og:title' content='Esdeveniment: <%= @event.title.gsub(/'/, "") %>' />
	<% end %>
	<% if @event.description.present? %>
	<meta property='og:description' content='<%= @event.description.gsub(/'/, "") %>' />
	<% else %>
	<meta property='og:description' content='<%= t(:no_description)%>' />
	<% end %>
	<meta property='og:type' content='event' />
	<meta property='og:url' content='<%= request.protocol+request.host+request.fullpath %>' />
	<meta property='og:image' content='<%= request.protocol+request.host+image_path("events.png") %>'>
	<meta property='og:site_name' content='<%=Configuration.value(:sitename)%>' />
	
<% elsif @debate.present?%>
	<% if @debate.title.present? %>
	<meta property='og:title' content='Debat: <%= @debate.title.gsub(/'/, "") %>' />
	<meta property='og:description' content='<%= @debate.description.gsub(/'/, "") %>' />
	<meta property='og:type' content='activity' />
	<meta property='og:url' content='<%= request.protocol+request.host+request.fullpath %>' />
	<meta property='og:image' content='<%= request.protocol+request.host+image_path("debats.png") %>'>
	<meta property='og:site_name' content='<%=Configuration.value(:sitename)%>' />
	<meta property='fb:admins' content='1570153931' />
	<meta property='fb:app_id' content='210773058935367' />
	<% end %>
<% else %>

	<meta property='og:title' content='<%=Configuration.value(:title_site).gsub(/'/, "") %>' />
	<meta property='og:description' content='<%=Configuration.value(:description_site).gsub(/'/, "") %>' />
	<meta property='og:type' content='website' />
	<meta property='og:url' content='<%= request.protocol+request.host+request.fullpath %>' />
	<meta property='og:image' content='<%= request.protocol+request.host+Configuration.image_url(:image_site)%>' />
	<meta property='og:site_name' content='<%=Configuration.value(:sitename)%>' />
	
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
	<div id="footer_container">
	<!--<div class="group"><% Configuration.value(:sitename)%>, <% t(:newspaper_group)%> <% link_to "pDigital","https://github.com/pekpon/pdigital" %></div>-->
	
	<div class="languaje foot_block">
		<span class="title">Idiomes</span><br><br>
		<%=image_tag "ca.png", :class => "flag" %> <%= link_to "Català", :locale => 'ca'%><br>
		<%=image_tag "es.png", :class => "flag" %> <%= link_to "Castellano", :locale => 'es' %>
	</div>
	
	<div class="foot_block">
		<span class="title">Continguts</span><br><br>
		<%= link_to t(:home), root_path %><br>
		<%= link_to t(:polls), polls_path %><br>
		<%= link_to t(:the_most), the_mosts_path %><br>
		<%= link_to t(:contact), contact_path %><br>
		<%= link_to t(:real_time), real_time_index_path %><br>
		<%= link_to t(:calendar), calendar_path %><br>
		<%= link_to t(:debates), debates_path %><br>
		<%= link_to t(:ads), "/#{I18n.locale}/contact" %>
	</div>
	
	<div class="license foot_block">
		<span class="title">Llicència</span><br><br>
		Sota llicència CC <br><a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/">Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License</a><br /><br>
			<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-nd/3.0/88x31.png" /></a>
	</div>
	
	<div class="foot_block">
		<span class="title"><%= Configuration.value(:sitename)%></span><br><br>
		<%= Configuration.value(:sitename)%> <%= Configuration.value(:foot_description)%><br><br><br>
		<%=link_to image_tag("foot_face.png", :class => "foot_social"), Configuration.value(:facebook_web), :target => "_blank"  %>
		<%=link_to image_tag("foot_twitter.png", :class => "foot_social"), Configuration.value(:twitter_web), :target => "_blank"  %>
		<%=image_tag "foot_rss.png", :class => "foot_social" %>
		<%=link_to image_tag("foot_you.png", :class => "foot_social"), Configuration.value(:youtube_channel), :target => "_blank" %>
	</div>
	</div>
	
</div>

app/views/shared/_header.html.erb
<div class="header">
  <%= link_to image_tag(Configuration.image_url(:head_image_left)), root_path %>
  <%= image_tag Configuration.image_url(:head_image_right), :width => "400px" %>
</div>

app/views/shared/_info_bar.html.erb
<% #if user_signed_in? %>
	<% # if current_user.username == "admin" %>
		<div id="info_bar">
			<span class="like">T'agrada <%= Configuration.value(:sitename)%>? </span>
			<iframe src="//www.facebook.com/plugins/like.php?locale=ca_ES&amp;href=<%=Configuration.value(:facebook_like_button)%>&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21&amp;appId=285250344834364" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:130px; height:21px;" allowTransparency="true"></iframe>
			
			<span class="stadistics">
				<i class="icon-comment"></i> <%=Configuration.value(:like_sentence)%>
			</span>
			
			<!--<span class="stadistics">
				<b>Artícles: </b><% Article.all(:conditions => { :active => true}).count %> |
				<b> Comentaris: </b><% ArticleComment.all(:conditions => { :active => true}).count %> |
				<b> Usuaris: </b><% User.all.count %>
			</span>-->
		</div>
	<% #  end %>
<% # end %>

app/views/shared/_navigation.html.erb
<div class="navigation">
	<ul>
      	<li class="portada <%= "active" if controller.controller_name == 'articles' %>"><%= link_to t(:home), root_path %></li>
	  	<li class="portada <%= "active" if controller.controller_name == 'polls' %>" ><%= link_to t(:polls), polls_path %></li>
		<li class="portada <%= "active" if controller.controller_name == 'the_mosts' %>"><%= link_to t(:the_most), the_mosts_path %></li>
		<li class="portada <%= "active" if controller.controller_name == 'contact' %>"><%= link_to t(:contact), contact_path %></li>
		<li class="portada <%= "active" if controller.controller_name == 'real_time' %>"><%= link_to t(:real_time), real_time_index_path %></li>
		<li class="portada <%= "active" if controller.controller_name == 'calendar' %>"><%= link_to t(:calendar), calendar_path %></li>
		<li class="portada <%= "active" if controller.controller_name == 'debates' %>"><%= link_to t(:debates), debates_path %></li>
		<li class="portada <%= "active" if controller.controller_name == 'commerces' %>"><%= link_to t(:commerces), commerces_path %></li>
			
		<%= raw(Configuration.links) %>
		
		<li class="search">
			
			<%= form_for :articles,:url => {:controller => :articles, :action => "search"}, :method => 'post', :class => "form-search" do %>
			<i class='icon-search icon-white'></i>
			    <%= text_field_tag :search, params[:search], :class => "search-query" %>
			    <%= submit_tag t(:search), :name => nil, :class => "btn btn-mini btn-primary" %>
			<% end %>
		</li>
      	
		<div class="clearFloat"></div>
   	</ul>
</div>

app/views/shared/_usersblock.html.erb
<div id="users_block">
	<% if user_signed_in? %>

		<!--<div class="user-panel">

		<span class="user-text"><b><%= t(:welcome)+" "+current_user.username %></b></span> 
		
		<span class="user-comments"><%= link_to raw("<i class='icon-comment'></i> <b>0</b>"), articles_path, :class => "btn btn-default btn-small" %></span>
		
	<ul class="user-dropdown">
	 <li class="dropdown">
	   <a class="dropdown-toggle" data-toggle="dropdown">
	     <span class="btn btn-small"><i class='icon-chevron-down '></i></span>
	   </a>
	   <ul class="dropdown-menu">
	     <li><a href="#">Perfil</a></li>
	     <li><a href="#">Enviar notícia</a></li>
	     <li class="divider"></li>
	     <li><%= link_to t(:sign_out), destroy_user_session_path, :method => :delete %></li>
	   </ul>
	 </li>
	</ul>
	
	</div>-->
	
			<p><b><%= t(:welcome)+" "+current_user.username %></b> <%= link_to raw("<i class='icon-off icon-white'></i>  "), destroy_user_session_path, :method => :delete, :class => "btn btn-danger btn-small btn-close", :rel => "tooltip", :title => t(:sign_out) %></p>
	
	<% else %>
	
		 <%= link_to t(:register), new_user_registration_path, :class => "btn btn-default btn-small"%>  <%= link_to t(:sign_in), new_user_session_path , :class => "btn btn-small btn-success"%>

	<% end %>
</div>