config/routes.rb
Pdigital::Application.routes.draw do

  match '/rss' => 'articles#rss'

  scope "/(:locale)" do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    devise_for :users
    match 'the_mosts/day' => 'the_mosts#day', :as => :day
    match 'the_mosts/month' => 'the_mosts#month', :as => :month
    match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
      
    resources :articles, :categories, :polls, :the_mosts, :contact, :comments, :real_time, :calendar, :events, :debates, :commerces

    match 'search/' => 'articles#search'
    
    root :to => 'articles#index'
    
    match 'contact' => 'contact#new', :as => 'contact', :via => :get
    match 'contact' => 'contact#create', :as => 'contact', :via => :post
    
  end

  match 'comments/vote/:id/:vote_type' => 'comments#vote', :as => :vote
  match 'comments/delete/:id' => 'comments#delete', :as => :delete
  
  match 'polls/vote/:id/:id_option' => 'polls#vote', :as => :vote_poll
  match 'polls/vote_result/:id' => 'polls#vote_result', :as => :vote_result
  match 'polls/poll_options/:id' => 'polls#poll_options', :as => :poll_options
  
  mount ImperaviRails::Engine => "/imperavi"
  

end

app/models/commerce.rb
class Commerce < ActiveRecord::Base
  
  has_many :comments, :as => :commentable
  belongs_to :user
  
  extend FriendlyId
  friendly_id :name, :use => :slugged
  
  validates :name, :street, :telephone, :presence => true
  
  validates :name, :length => { :maximum => 150 }
  validates :street, :length => { :maximum => 200 }
  validates :telephone, :length => { :maximum => 15 }
  
  has_attached_file :image, :styles => { :large => "600x600>", :inside => "300x300#", :index => "260x170#" }
  
end

app/controllers/commerces_controller.rb
class CommercesController < ApplicationController
  
  def index
    commerces1 = Commerce.where(:active => true, :pro => true).order("name ASC")
    commerces2 = Commerce.where(:active => true, :pro => nil).order("name ASC")
    commerces3 = Commerce.where(:active => true, :pro => false).order("name ASC")
    
    @commerces = commerces1 + commerces2 + commerces3
    @commerce = Commerce.new
    
    respond_to do |format|
      format.html  # index.html.erb
    end
    
  end
  
  def show
    
    @commerce = Commerce.find(params[:id])
    @comments = @commerce.comments.where(:active => true).order("created_at ASC")
    
    respond_to do |format|
      format.html  # show.html.erb
    end
    
  end
  
  def create
    if params[:commerce][:active].to_i == 1
      if simple_captcha_valid?
        @commerce = Commerce.new(params[:commerce])
        @commerce.active = true
        @commerce.user = current_user

        respond_to do |format|
          if @commerce.save
            format.html  { redirect_to(commerces_path,
                          :notice => t(:commerce_added)) }
          else
            format.html  { redirect_to(commerces_path,
                          :alert => t(:commerce_error)) }
          end
        end
      
      else
        respond_to do |format|
            format.html  { redirect_to(commerces_path,
                          :alert => t(:captcha_error)) }
          end
      end
      
    else
      respond_to do |format|
          format.html  { redirect_to(commerces_path,
                        :alert => t(:active_error)) }
        end
    end
    
  end
end

app/helpers/commerces_helper.rb
module CommercesHelper
end

app/views/commerces/index.html.erb
<%= stylesheet_link_tag "commerces" %>

<div class="white">
	<div id="section_header"><%= t(:commerces) %></div>
		<div class="add_commerce">
			<a class="btn btn-large btn-primary btn-afegir" data-toggle="modal" href="#myModal"><i class='icon-plus icon-white'></i> <%= t(:new_commerce)%></a>
		</div>
		
			<% count = 1 %>
			<% @commerces.each do |c| %>
			
			<% count = count - 1 %>
			<% if count == 0 %>
			<div class="content">
				<% count = 3 %>
			<% end %>
			
			<div class="box">
				<div class="image">
					<% if c.pro == true and c.image.url(:index) != "/images/index/missing.png" %>
						<%= link_to (image_tag c.image.url(:index)), commerce_path(c) %>
					<% else %>
						<%= link_to (image_tag("commerce.png")), commerce_path(c) %>
					<% end %>
				</div>
				
				<%= link_to raw("<div class='name'>#{c.name}</div>"), commerce_path(c) %>
			</div>
			
			<% if count == 1 %>
				<%= raw("</div>") %>
			<% end %>
			
			<% end %>
			
			<% if count > 1 %>
				<%= raw("</div>") %>
			<% end %>
			
</div>

<!-- MODAL -->
<div class="modal hide fade" id="myModal">
  <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h3><%=t(:new_commerce)%></h3>
  </div>
	<% if user_signed_in? %>
  		<div class="modal-body">
			<%= form_for(@commerce) do |f| %>
			  <% if @commerce.errors.any? %>
			  <div id="errorExplanation">
			    <h2><%= pluralize(@commerce.errors.count, "error") %> prohibited
			        this post from being saved:</h2>
			    <ul>
			    <% @commerce.errors.full_messages.each do |msg| %>
			      <li><%= msg %></li>
			    <% end %>
			    </ul>
			  </div>
			  <% end %>

			  <div class="field">
			    <%= f.label t(:commerce_name) %>
			    <%= f.text_field :name, :id => "commerce_text_field" %>
			  </div>
			  <div class="field">
			    <%= f.label t(:street) %>
			    <%= f.text_field :street, :id => "commerce_text_field" %>
			  </div>
			<div class="field">
			    <%= f.label t(:telephone) %>
			    <%= f.text_field :telephone, :id => "commerce_text_field" %>
			  </div>
			<div class="field">
			    <%= show_simple_captcha %>
			  </div>
			<div class="field">
			    <%= f.check_box :active %> <span class="active"><%= t(:authorized) %></span>
			  </div>

		</div>
		<div class="modal-footer">
			<div class="actions">
			    <%= submit_tag t(:create), :class => "btn btn-success" %>
			  </div>
			<% end %>
		</div>
	<% else %>
    	<div class="modal-body">
			<div class="alert alert-error" style="margin-right:15px"><%=t(:need_login)%></div>
		</div>
		<div class="modal-footer">
			<%= link_to t(:sign_in), user_session_path, :class => "btn btn-success" %> o <%= link_to t(:register), new_user_registration_path, :class => "btn btn-primary"%>
		</div>
	<% end %>
</div>

app/views/commerces/show.html.erb
<%= stylesheet_link_tag "commerces","comments" %>

<div class="white">
	<div id="section_header"><%= @commerce.name %></div>
	
	<div class="content">
		
		<div class="left_col">
			
			<div class="info">
				<i class="icon-flag"></i>
				<b> <%=t(:street)%>: </b>
				<%= @commerce.street %>
			</div>
			<div class="info">
				<i class="icon-signal"></i>
				<b> <%=t(:telephone)%>: </b>
				<%= @commerce.telephone %>
			</div>
			
			<% if @commerce.email.present? and @commerce.pro == true %>
			<div class="info label1">
				<i class="icon-envelope"></i>
				<b> <%=t(:email)%>: </b>
				<%= @commerce.email %>
			</div>
			<% end %>
			
			<% if @commerce.web.present? and @commerce.pro == true %>
			<div class="info label1">
				<i class="icon-home"></i>
				<b> <%=t(:web)%>: </b>
				<%= @commerce.web %>
			</div>
			<% end %>
			
			<% if @commerce.schedule.present?%>
			<div class="info label2">
				<i class="icon-time"></i>
				<b> <%=t(:schedule)%>: </b><br/>
				<%= raw(@commerce.schedule.gsub("\n","<br/>")) %>
			</div>
			<% end %>
			
			<% if @commerce.pro != true and @commerce.user == current_user %>
			<!-- NO PREMIUM USER ADVISE -->
			<br/>
			<div id="config_tab">
				<i class="icon-th icon-white"></i> <%= t(:configuration) %>
			</div>
			<ul>
				<li class="new_list">
					<i class="icon-plus"></i> <%= link_to t(:add_image), contact_path() %>
				</li>
				<li class="new_list">
					<i class="icon-plus"></i> <%= link_to t(:add_email), contact_path() %>
				</li>
				<li class="new_list">
					<i class="icon-plus"></i> <%= link_to t(:add_scheudle), contact_path() %>
				</li>
				<li class="new_list">
					<i class="icon-plus"></i> <%= link_to t(:add_map), contact_path() %>
				</li>
				<li class="new_list">
					<i class="icon-plus"></i> <%= link_to t(:add_comments), contact_path() %>
				</li>
			</ul>
			<div class="alert alert-error">
				<%= raw(t(:config_explain)) %>
			</div>
			<% end %>
			<!-- END ADVISE -->
			
			<% if @commerce.map_code.present? and @commerce.pro == true %>
			<br/>
			<div>
				<%= raw(@commerce.map_code) %>
			</div>
			<% end %>
			
			<% if @commerce.pro == true %>
			<div id="commerce_comment_content">

			<%= render :partial => 'comments/show', :locals => {:id => @commerce.id, :type => "Commerce"} %>
			</div>
			<% end %>
			
		</div>
		
		<div class="right_col">
			<div class="image inside_image">
				<% if @commerce.pro == true and @commerce.image.url(:index) != "/images/index/missing.png" %>
					<%= image_tag @commerce.image.url(:inside) %>
				<% else %>
					<%= image_tag("commerce.png") %>
				<% end %>
			</div>
		</div>
		<% @commerce.telephone %>
		
	</div>
</div>